### ISSUE TITLE
Identify the parts of the application that are consuming the most resources and taking the most time to execute.

### ISSUE THREAD

**Issue by IstiaqulAlam** [gitSean23/AidUI#3]
Time: 2 days
Dependencies: None
Assignments: Istiaqul
Milestone: Sprint 1
Acceptance Criteria: List the things that take the longest time to execute in decreasing order so we can focus on the one that takes the longest time

**Comment by Greesh12** [comment]
This turned out to be everything that has to do with the evaluation dataset. We couldn't really generate a list because there were a lot of dependencies, however we created a list of all the dependencies that are actually needed to make the program run.
